unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-a               # Leader key: Ctrl+a
set -g base-index 1             # start indexing windows at 1 instead of 0
set -g mouse on                 # mouse controls on
set -g escape-time 0            # zero-out escape time delay
set -g renumber-windows on      # renumber all windows when any window is closed

#LDUR keys 
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key w kill-pane
bind-key W kill-window

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_window_number "#I"
set -g @catppuccin_window_text " #W "
set -g @catppuccin_window_current_text " #W "
set -g @catppuccin_window_current_number "#I"
set -ogq @catppuccin_window_current_number_color "#{@thm_blue}"
set -g @catppuccin_directory_text "#{b:pane_current_path}"


# Make the status line pretty and add some modules
# 1. Transparency (The Official v2 Way)
set -g @catppuccin_status_background "none"

set-option -g status-position top
set -g default-terminal "tmux-256color"
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}#[bg=#{@thm_surface_0}]#[bg=#{@_ctp_status_bg}]#[none]"


run '~/.tmux/plugins/tpm/tpm'
run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'
